# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rpc/command.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'rpc/command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

from google.protobuf.empty_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11rpc/command.proto\x12\nTaskMaster\x1a\x1bgoogle/protobuf/empty.proto\"+\n\x06Target\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0binstance_id\x18\x02 \x03(\r\"\x1c\n\nTaskStatus\x12\x0e\n\x06status\x18\x01 \x01(\t2\x8a\x03\n\x06Runner\x12\x33\n\x05start\x12\x12.TaskMaster.Target\x1a\x16.google.protobuf.Empty\x12\x32\n\x04stop\x12\x12.TaskMaster.Target\x1a\x16.google.protobuf.Empty\x12\x35\n\x07restart\x12\x12.TaskMaster.Target\x1a\x16.google.protobuf.Empty\x12\x38\n\x06reload\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12:\n\x08shutdown\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x34\n\x04list\x12\x16.google.protobuf.Empty\x1a\x12.TaskMaster.Target0\x01\x12\x34\n\x06status\x12\x12.TaskMaster.Target\x1a\x16.TaskMaster.TaskStatusP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc.command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TARGET']._serialized_start=62
  _globals['_TARGET']._serialized_end=105
  _globals['_TASKSTATUS']._serialized_start=107
  _globals['_TASKSTATUS']._serialized_end=135
  _globals['_RUNNER']._serialized_start=138
  _globals['_RUNNER']._serialized_end=532
# @@protoc_insertion_point(module_scope)
