tasks:
    echo:
        command: "echo Boujour"
        replicas: 1
        start_on_launch: true
        start_attempts: 2
        restart: "on_failure"
        success_exit_codes: [0, 1]
        start_timeout: 3

    sleep:
        command: "sleep infinity"
        replicas: 1
        start_on_launch: true
        restart: "on_failure"
        success_exit_codes: [0, 1]
        start_timeout: 2
        start_attempts: 5
        shutdown_signal: "SIGINT"
        shutdown_timeout: 15
        # stderr: "/var/log/apache_stderr.log"
        # pwd: "/etc/apache2"
